#define IMPORT_ERROR_H

typedef enum errors
{
    ERROR_EMPTY_ARRAY = 1,
    ERROR_EMPTY_STACK,
    ERROR_EMPTY_QUEUE,
    ERROR_EMPTY_LINKED_LIST,
    ERROR_MPQUEUE_MAXIMUM_PRIORITY_EXCEEDED,
    ERROR_LINKED_LIST_INDEX_OUT_OF_RANGE,
} Errors;